/**
 * Property-based tests for PINService.
 *
 * Feature: stellar-pay, Property 14: PIN validation accepts only 4-6 digit strings
 * Feature: stellar-pay, Property 15: PIN hash round-trip
 * Feature: stellar-pay, Property 16: Lockout after 5 consecutive failures
 *
 * Validates: Requirements 4.1, 4.2, 4.5, 13.5
 *
 * Uses fast-check to generate arbitrary inputs and verify PINService invariants
 * across many randomized cases.
 */

import fc from 'fast-check';
import bcrypt from 'bcryptjs';
import { jest } from '@jest/globals';
import { isValidPinFormat, verifyPin } from '@/lib/services/pin.service';
import { prisma } from '@/lib/prisma';

// Type the mocked Prisma client for lockout tests.
const mockPrisma = prisma as unknown as {
  user: {
    findUnique: jest.Mock;
    update: jest.Mock;
  };
};

describe('PINService — Property Tests', () => {
  // ── Property 14: PIN validation accepts only 4-6 digit strings ──────

  describe('Property 14: PIN validation accepts only 4-6 digit strings', () => {
    // Feature: stellar-pay, Property 14: PIN validation accepts only 4-6 digit strings
    it('accepts any string of exactly 4-6 numeric digits', () => {
      /**
       * Validates: Requirements 4.1
       *
       * For any integer in the range [1000, 999999], its string representation
       * is a valid 4-6 digit PIN and isValidPinFormat should return true.
       */
      fc.assert(
        fc.property(
          fc.integer({ min: 1000, max: 999999 }).map(String),
          (pin) => {
            return isValidPinFormat(pin) === true;
          }
        ),
        { numRuns: 20 }
      );
    });

    // Feature: stellar-pay, Property 14: PIN validation accepts only 4-6 digit strings
    it('rejects arbitrary strings that are not 4-6 digit sequences', () => {
      /**
       * Validates: Requirements 4.1
       *
       * For any arbitrary string generated by fast-check, isValidPinFormat
       * should return true if and only if the string matches /^\d{4,6}$/.
       */
      fc.assert(
        fc.property(fc.string(), (s) => {
          const expected = /^\d{4,6}$/.test(s);
          return isValidPinFormat(s) === expected;
        }),
        { numRuns: 20 }
      );
    });
  });

  // ── Property 15: PIN hash round-trip ────────────────────────────────

  describe('Property 15: PIN hash round-trip', () => {
    // Feature: stellar-pay, Property 15: PIN hash round-trip
    it('bcrypt hash of a valid PIN verifies correctly with the original PIN', async () => {
      /**
       * Validates: Requirements 4.2
       *
       * For any valid PIN (4-6 digits), hashing with bcrypt (cost 12) and then
       * comparing the original PIN against the hash should return true.
       */
      await fc.assert(
        fc.asyncProperty(
          fc.integer({ min: 1000, max: 999999 }).map(String),
          async (pin) => {
            const hash = await bcrypt.hash(pin, 12);
            const matches = await bcrypt.compare(pin, hash);
            return matches === true;
          }
        ),
        { numRuns: 20 }
      );
    }, 120_000);

    // Feature: stellar-pay, Property 15: PIN hash round-trip
    it('bcrypt hash of a valid PIN does not verify with a different PIN', async () => {
      /**
       * Validates: Requirements 4.2
       *
       * For any two distinct valid PINs, hashing the first and comparing
       * the second against that hash should return false.
       */
      await fc.assert(
        fc.asyncProperty(
          fc.integer({ min: 1000, max: 999999 }).map(String),
          fc.integer({ min: 1000, max: 999999 }).map(String),
          async (pin1, pin2) => {
            fc.pre(pin1 !== pin2);
            const hash = await bcrypt.hash(pin1, 12);
            const matches = await bcrypt.compare(pin2, hash);
            return matches === false;
          }
        ),
        { numRuns: 20 }
      );
    }, 120_000);
  });

  // ── Property 16: Lockout after 5 consecutive failures ───────────────

  describe('Property 16: Lockout after 5 consecutive failures', () => {
    // Feature: stellar-pay, Property 16: Lockout after 5 consecutive failures
    it('triggers lockout on exactly the 5th consecutive failed PIN attempt', async () => {
      /**
       * Validates: Requirements 4.5, 13.5
       *
       * For any valid PIN and a different wrong PIN, simulating 5 consecutive
       * failures via verifyPin should result in a lockout being set on the 5th
       * failure (failedPinAttempts=5 and pinLockedUntil set to a future date),
       * while failures 1-4 should NOT trigger lockout.
       *
       * We pre-compute a bcrypt hash for a fixed "correct" PIN outside the
       * property loop. The property varies the wrong PIN to prove the lockout
       * logic is independent of which wrong PIN is submitted.
       */
      const correctPin = '123456';
      const pinHash = await bcrypt.hash(correctPin, 12);

      await fc.assert(
        fc.asyncProperty(
          // Generate wrong PINs that differ from correctPin
          fc.integer({ min: 1000, max: 999999 })
            .filter((n) => String(n) !== correctPin)
            .map(String),
          async (wrongPin) => {
            // Simulate attempts 1 through 4: no lockout should occur.
            for (let attempt = 0; attempt < 4; attempt++) {
              mockPrisma.user.findUnique.mockResolvedValue({
                pinHash,
                failedPinAttempts: attempt,
                pinLockedUntil: null,
              });
              mockPrisma.user.update.mockResolvedValue({});

              const result = await verifyPin('test-user', wrongPin);
              expect(result).toBe(false);

              const updateCall = mockPrisma.user.update.mock.calls[
                mockPrisma.user.update.mock.calls.length - 1
              ][0];
              // Should NOT have lockout set for attempts 1-4
              expect(updateCall.data.failedPinAttempts).toBe(attempt + 1);
              expect(updateCall.data.pinLockedUntil).toBeNull();
            }

            // 5th attempt: lockout should trigger
            mockPrisma.user.findUnique.mockResolvedValue({
              pinHash,
              failedPinAttempts: 4,
              pinLockedUntil: null,
            });
            mockPrisma.user.update.mockResolvedValue({});

            const result5 = await verifyPin('test-user', wrongPin);
            expect(result5).toBe(false);

            const lockoutCall = mockPrisma.user.update.mock.calls[
              mockPrisma.user.update.mock.calls.length - 1
            ][0];
            expect(lockoutCall.data.failedPinAttempts).toBe(5);
            expect(lockoutCall.data.pinLockedUntil).toBeInstanceOf(Date);

            // Lockout should be approximately 15 minutes in the future.
            const lockUntil = lockoutCall.data.pinLockedUntil as Date;
            const diffMinutes =
              (lockUntil.getTime() - Date.now()) / (1000 * 60);
            expect(diffMinutes).toBeGreaterThan(14);
            expect(diffMinutes).toBeLessThanOrEqual(15.5);

            return true;
          }
        ),
        { numRuns: 20 }
      );
    }, 120_000);
  });
});
